### ISSUE TITLE
Why not use jju from NPM?

### ISSUE THREAD

**Issue by blakeembrey** [sindresorhus/parse-json#1]
I noticed the vendor scripts have been copied out from [jju](https://www.npmjs.com/package/jju) - why wouldn't you just use it from NPM instead?

**Comment by sindresorhus** [comment]
The published jju package contains a lot of junk and I only needed that one method. I could have submitted a PR to get down the size, but I've previously tried that with that author and failed, so was easier to just do it like this.

**Comment by blakeembrey** [comment]
@sindresorhus Though it took a little time, I asked and he didn't seem to have any problem with it https://github.com/rlidwka/jju/issues/14#issuecomment-139827974
