### ISSUE TITLE
No easy way to tell what changed between releases

### ISSUE THREAD

**Issue by kumar303** [sindresorhus/parse-json#15]
Hi. I noticed that when 3.0.0 and 4.0.0 were [released](https://github.com/sindresorhus/parse-json/releases), they did not contain any release notes. I cannot find a changelog anywhere -- maybe I'm missing it?

According to [semver](https://semver.org/) (which most NodeJS packages follow), major version increases like this indicate breaking changes. Did anything break in both of these releases?

**Comment by SamVerschueren** [comment]
We keep our commit messages clean which clearly shows what changed https://github.com/sindresorhus/parse-json/commits/master

**Comment by kumar303** [comment]
Thanks for the quick reply. Something like [*Meta tweaks*](https://github.com/sindresorhus/parse-json/commit/148781b95c30ae9a263cfd27638defe1cc21c547) isn't clear to me at a glace; I'd have to open the patch to see what it is. 

Well, anyway, if that's the approach, it would be helpful to me if you at least included comparison links for each release, like:

* https://github.com/sindresorhus/parse-json/compare/v2.2.0...v3.0.0
* https://github.com/sindresorhus/parse-json/compare/v3.0.0...v4.0.0

I definitely see how using commit messages as a changelog is easier but since there is generally a bit of noise, you could also use something like [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to cut out the noise.
