### ISSUE TITLE
Not very helpful

### ISSUE THREAD

**Issue by quinton-ashley** [sindresorhus/parse-json#18]
I get even less information than from JSON.parse, which gave an unexpected character T at 3987209

ErrorEXError {name: "JSONError"}
name
:
"JSONError"
message
:
"Cannot parse

**Comment by Hoishin** [comment]
It seems an issue with https://github.com/zkat/json-parse-better-errors

BTW, `Cannot parse` message is output when you try to parse non-string. If the error message is "Cannot parse", I think it failed to turn the non-string thing into string.

**Comment by quinton-ashley** [comment]
yes the issue was an unescaped quote mark in a string.  It'd be nice to know the line number and character position

**Comment by sindresorhus** [comment]
Please open an issue on https://github.com/zkat/json-parse-better-errors :)

**Comment by quinton-ashley** [comment]
I'm not the one using json-parse-better-errors you guys are.
