### ISSUE TITLE
Why bother with built-in parsing to begin with?

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/parse-json#2]
I am all for allowing the native implementation handle it, but why parse twice in the event the native implementation doesn't work? If the idea is that the supplied (vendor) parser is going to do a better job than the native, why not just use it instead and cut out a call and a whole parsing session?

**Comment by sindresorhus** [comment]
Native parser is faster and better. I'm optimizing for the common case where you don't have an error. The JS parser is only used for its better error message. In the event of an error the overhead of parsing twice doesn't matter.

**Comment by Qix-** [comment]
Got it, makes sense.
