### ISSUE TITLE
Remove Babel dependency

### ISSUE THREAD

**Issue by Keavon** [sindresorhus/parse-json#27]
Babel is not necessary. It should be removed. It sucks having it included in random sub-sub-sub dependencies, which this package is.

**Comment by sindresorhus** [comment]
Babel is not a dependency, `@babel/code-frame` is.

**Comment by Keavon** [comment]
I see, thanks for pointing out that there's a difference. Could you please excuse my ignorance and describe briefly what `@babel/code-frame` does? Unfortunately the [website for it](https://babeljs.io/docs/en/babel-code-frame) doesn't actually describe that and I can't find anything else from researching it. What necessary function does it perform?

For a little bit of background context, I was searching my dependency tree for Babel because I know it is notoriously bad at bloating the dependency chain of projects. I didn't realize `@babel/code-frame` is distinct from the rest of Babel, but now I'm wondering what its relationship is with the rest of Babel and the ecosystem.

Thank you!

**Comment by sindresorhus** [comment]
It shows the source code of where the error originated with an arrow pointing to it, to make errors more user-friendly. See an example in the readme: https://github.com/sindresorhus/parse-json#usage

**Comment by Keavon** [comment]
Ah I see, thank you for explaining! Yes, I definitely understand how that's a vital dependency for `parse-json`. It seems like they should just release that as its own package outside the Babel namespace, at least to avoid scaring people like me about how much Babel is prevalent in project dependency trees (i.e. it isn't, but it looked like it!). Cheers!
