### ISSUE TITLE
Broken change after migrating to ES6

### ISSUE THREAD

**Issue by yangpu** [sindresorhus/parse-json#28]
Our project is broken after the new release of parse-json, and the error as follow:

`
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/parse-json/index.js from node_modules/@lykmapipo/common/lib/index.js not supported.
`
and the dependency tree is:

`
mongoose-gridfs -> @lykmapipo/mongoose-common -> @lykmapipo/common -> parse-json
`

However @lykmapipo/common always install the latest parse-json:

`
"parse-json": ">=5.2.0"
`

Could you make "require" and "import" both? thanks a lot.

**Comment by sindresorhus** [comment]
Please read the release notes.
