### ISSUE TITLE
Pin version of `lines-and-columns` dependency 

### ISSUE THREAD

**Issue by DerYeger** [sindresorhus/parse-json#30]
`lines-and-columns` had a few updates recently, and since they weren't using semantic versioning correctly it broke this library.

(See https://www.npmjs.com/package/lines-and-columns).

This could be fixed by pinning the version number to 1.1.6.

**Comment by DerYeger** [comment]
See [this](https://github.com/DerYeger/magdalena-jirku/runs/4275511030?check_suite_focus=true) GitHub Action log for an occurrence of the issue.

**Comment by revelt** [comment]
I can confirm, `1.2.0` is what was meant to be `2.0.0`, I was attempting to do a release and CI is failing. `npm ls` shows it's consumed by `lerna` consuming `meow` and my direct `meow` instances... Good thing it's weekend, hope this will be sorted by Monday...

**Comment by Dreaming-Codes** [comment]
Now solved, if you want to upgrade to the new version you can use this: #32

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/parse-json/commit/a244a17ff8ee0e49b33e5c95aa49ffabf567fed6
