### ISSUE TITLE
problem using in Vite

### ISSUE THREAD

**Issue by tiye** [sindresorhus/parse-json#35]
I got error `TypeError: Cannot read properties of undefined (reading 'close')` after running Vite build using this package. Error traced:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/449224/210224669-96cf3460-74fa-4331-8045-bf8e65735e05.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/449224/210224746-ff36a663-7166-4e93-b883-d93f377ddd50.png">
<img width="267" alt="image" src="https://user-images.githubusercontent.com/449224/210224763-050f6e51-775d-4d8f-97fc-68000f5fec03.png">

it works fine in dep demo. I guess it's because this package is referencing very old chalk 2.x which Vite does not optimizes well.

any plan to upgrade dependency or bypass the issue?

**Comment by sindresorhus** [comment]
`chalk` comes from the `@babel/code-frame`, which does not have any update, so you should open an issue on `@babel/code-frame` instead to get them to upgrade.

**Comment by tiye** [comment]
referenced https://github.com/babel/babel/discussions/15321 .
