### ISSUE TITLE
Remove error-ex as dependency

### ISSUE THREAD

**Issue by prisis** [sindresorhus/parse-json#38]
Would you accept a PR that will remove "error-ex" as a dependency?

The current implementation could be switched to 

Example:
```
class JSONError extends Error {
  constructor(message) {
    super(message);
    this.name = 'JSONError';
    this.fileName = undefined
    this.codeFrame = undefined
    this.rawCodeFrame = undefined
  }
}
```

**Comment by sindresorhus** [comment]
Yes

**Comment by fisker** [comment]
`error-ex` has the ability to show different message when assign a `fileName` to error, I think it's usefule.

**Comment by prisis** [comment]
You mean this part `fileName: errorEx.append('in %s')`?

If yes this could be done like 

```
if (filename) {
		jsonError.fileName = `in ${filename}`;
	}
```
