### ISSUE TITLE
Ambiguous errors on Node 7.0.0

### ISSUE THREAD

**Issue by mhkeller** [sindresorhus/parse-json#6]
If I have an invalid json file such as `{wrong: }`, the current error on node 0.11 through 6.9.1 is the following

```
        throw jsonErr;
        ^
JSONError: Unexpected token 'w' at 1:3
{ wrong: }
  ^
```

On Node 7.0.0 the error is

```
        Object.defineProperty(this, 'stack', stackDescriptor);
               ^

TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
```

**Comment by sindresorhus** [comment]
The error is probably coming from here: https://github.com/Qix-/node-error-ex/blob/4547099fb972af6c793519a2550fcee9c8b1c063/index.js#L79

// @Qix-

**Comment by Qix-** [comment]
The PR didn't fix it, I'm still working on a fix. Sorry for the delay, we had holiday the last few days.

**Comment by Qix-** [comment]
Can everyone `npm i` and re-run their tests? :) Bugfix should be published.

// cc @sindresorhus @eight04 @mhkeller
