### ISSUE TITLE
Does this package work in browser?

### ISSUE THREAD

**Issue by honzajavorek** [sindresorhus/parse-json#8]
I have some problems running this package in browser (https://github.com/apiaryio/gavel.js/pull/85). Is browser a supported runtime for this package? I can't see any mention of this in the docs.

**Comment by SamVerschueren** [comment]
If you use something like webpack, probably yes. 
We aim for Node.js though, not the browser. So if you have issues with webpack and uglifyjs, don't use the latest version. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446
