### ISSUE TITLE
Append line / column of error after file

### ISSUE THREAD

**Issue by anfedorov** [sindresorhus/parse-json#9]
It came up in [this issue](https://github.com/lerna/lerna/issues/854#issuecomment-318181789) that terminals like iTerm2 for macOS and editors like Sublime Text recognize references to lines and columns appended to a file like this:

    /Users/andrey/code/foo/package.json:7:31

Would you accept a pull request editing the error format and documentation to conform to this style? It would allow folks to get to the exact point of the error with a single click & hence solve it most efficiently.

**Comment by sindresorhus** [comment]
Yes, looks useful :)

**Comment by anfedorov** [comment]
apologies, missed the comment on the other PR. #11 should be better!
